version: 2

builds:
  - binary: gh-attach
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
